export const DEMO_COMPANY_ID = "demo-company";
export const DEMO_ORGANIZATION_ID = "demo-organization";

export const demoContactRows = [
  {
    demo_contact_id: "1",
    first_name: "Alex",
    last_name: "Rivera",
    email_address: "alex@example.com",
    contact_number: "+1 555 0100",
    home_country: "US",
    preferred_channel: "phone_email",
    notes: "Share product updates outside weekends.",
    company_id: DEMO_COMPANY_ID,
    organization_id: DEMO_ORGANIZATION_ID,
    created_at: "2024-12-01T10:00:00.000Z",
    updated_at: "2024-12-05T08:30:00.000Z",
  },
  {
    demo_contact_id: "2",
    first_name: "Jamie",
    last_name: "Santos",
    email_address: "jamie@demo.com",
    contact_number: "+1 555 0101",
    home_country: "CA",
    preferred_channel: "email",
    notes: "Always include invoice copies when contacting.",
    company_id: DEMO_COMPANY_ID,
    organization_id: DEMO_ORGANIZATION_ID,
    created_at: "2025-01-15T15:12:00.000Z",
    updated_at: "2025-01-18T09:45:00.000Z",
  },
  {
    demo_contact_id: "3",
    first_name: "Samira",
    last_name: "Vega",
    email_address: "samira@demo.com",
    contact_number: "+1 555 0102",
    home_country: "GB",
    preferred_channel: "sms",
    notes: "No SMS after 7pm.",
    company_id: DEMO_COMPANY_ID,
    organization_id: DEMO_ORGANIZATION_ID,
    created_at: "2025-02-03T11:20:00.000Z",
    updated_at: "2025-02-07T14:55:00.000Z",
  },
  {
    demo_contact_id: "4",
    first_name: "Jin",
    last_name: "Park",
    email_address: "jin@demo.com",
    contact_number: "+1 555 0103",
    home_country: "KR",
    preferred_channel: "email",
    notes: "Prefers short summaries.",
    company_id: DEMO_COMPANY_ID,
    organization_id: DEMO_ORGANIZATION_ID,
    created_at: "2025-02-25T09:15:00.000Z",
    updated_at: "2025-03-01T13:40:00.000Z",
  },
] as const;
