import { defineColumns } from "../constructors/define-columns";
import type { ResourceFieldSpec, ResourceRoute } from "../resource-types";
import { countryCodes, timezoneKeys } from "@/lib/constants";
import { customerJurisdictionDataSource } from "./resource-route-data-sources";

export const customerResourceRoutes: Record<string, ResourceRoute> = {
  customers: {
    table: "customers",
    deferNewButtonToHeader: true,
    // searchBy: "name,email,contact_name,company_number,status",
    deferSubtitleToHeader: true,
    deferTitleToHeader: true,
    deferToHeader: true,
    athenaModel: "customers",
    
    idColumn: "customer_id",
    create: {
      scope: "",
      required: [],
      optional: [],
      columns: [
        { column_name: "name" },
        { column_name: "email" },
        {
          column_name: "customer_id",
          hidden: true,
          default_value: "uuid_v4_gen",
        },
        {
          column_name: "organization_id",
          hidden: true,
          default_value: "user.organization",
        },
      ],
    },
    edit: {
      enabled: true,
      deniedColumns: ["customer_id"],
    },
    drilldownRoutePrefix: "/v2/customers",
    force_remove_back_button_store_on_index_resource: true,
    avatar_column: "avatar",
    enableNewResourceCreation: true,
    page_label: "Customers",
    enableSearch: false,
    categories: ["Basic", "Address", "Business", "Tax", "Legal", "Dates"],
    columns: defineColumns([
      {
        column_name: "name",
        category: "Basic",
        minWidth: 200,
        maxWidth: 200,
        order: 1,
      },
      {
        column_name: "email",
        category: "Basic",
        data_type: "string",
        order: 2,
      },
      { column_name: "phone", data_type: "text", category: "Basic" },
      { column_name: "website", data_type: "text", category: "Basic" },
      { column_name: "contact_name", data_type: "text", category: "Basic"},
      {
        column_name: "status",
        data_type: "string",
        field_type: "select",
        order: 3,
        update_column: "status",
        update_table: "customers",
        update_id_column: "customer_id",
        options: [
          { label: "Active", value: "active" },
          { label: "Inactive", value: "inactive" },
        ],
      },
      { column_name: "vat_id", data_type: "text", category: "Business" },
      {
        column_name: "company_number",
        data_type: "text",
        category: "Business",
      },
      {
        column_name: "note",
        data_type: "text",
        category: "Basic",
        field_type: "textarea",
      },
      { column_name: "street_address", data_type: "text", category: "Address" },
      { column_name: "address_line_2", data_type: "text", category: "Address" },
      { column_name: "city", data_type: "text", category: "Address" },
      {
        column_name: "state_province_region",
        data_type: "text",
        category: "Address",
      },
      { column_name: "postal_code", data_type: "text", category: "Address" },
      {
        column_name: "country",
        data_type: "text",
        category: "Address",
        field_type: "select",
        options: Object.entries(countryCodes).map(([label, value]) => ({
          label,
          value,
        })),
      },
      { column_name: "email", data_type: "text" },
      {
        column_name: "size",
        data_type: "text",
        category: "Business",
        field_type: "select",
        options: [
          { label: "1-9", value: "1-9" },
          { label: "10-49", value: "10-49" },
          { label: "50-99", value: "50-99" },
          { label: "100+", value: "100+" },
        ],
      },
      {
        column_name: "customer_type_id",
        data_type: "text",
        category: "Business",
      },
      { column_name: "phone", data_type: "text" },
      { column_name: "website", data_type: "text" },
      { column_name: "legal_form", data_type: "text", category: "Business" },
      { column_name: "owner", data_type: "text", category: "Business" },
      {
        column_name: "vat_return_frequency",
        data_type: "text",
        category: "Tax",
      },
      {
        column_name: "icp_return_frequency",
        data_type: "text",
        category: "Tax",
      },
      { column_name: "cash_management", data_type: "text", category: "Tax" },
      { column_name: "subject_to_vat", data_type: "boolean" },
      { column_name: "created_at", data_type: "timestamp", hidden: true },
      { column_name: "name", data_type: "text" },
      { column_name: "main_contact_id", data_type: "uuid" },
      { column_name: "company_id", data_type: "uuid" },
      { column_name: "domain", data_type: "text" },
      {
        column_name: "administration",
        data_type: "text",
        category: "Business",
      },
      {
        column_name: "contract_start_date",
        data_type: "number",
        category: "Dates",
      },
      {
        column_name: "accounting_start_date",
        data_type: "number",
        category: "Dates",
      },
      { column_name: "closing_enabled", data_type: "boolean", category: "Tax" },
      { column_name: "self_booking", data_type: "boolean", category: "Tax" },
      { column_name: "global_company_id", data_type: "uuid" },
      { column_name: "customer_jurisdiction", data_type: "text" },
      { column_name: "account_manager", data_type: "text" },
      { column_name: "archive_hash", data_type: "text" },
      {
        column_name: "customer_jurisdiction_id",
        data_type: "uuid",
        category: "Business",
        label: "Jurisdictions",
        field_type: "select",
        editor: {
          type: "select",
          data_source: customerJurisdictionDataSource,
        },
        editable: {
          type: "select",
          update_table: "customers",
          update_id_column: "customer_id",
          update_column: "customer_jurisdiction_id",
          data_source: customerJurisdictionDataSource,
        },
      },
      { column_name: "status", data_type: "text" },
      { column_name: "allow_self_accounting", data_type: "boolean" },
      { column_name: "companies", data_type: "number" },
      { column_name: "users", data_type: "number" },
      { column_name: "workflow", data_type: "number" },
      { column_name: "tickets", data_type: "number" },
      { column_name: "questions", data_type: "number" },
      { column_name: "is_overdue", data_type: "boolean" },
      { column_name: "data_provider", data_type: "text" },
      { column_name: "portal", data_type: "text" },
      { column_name: "data_provider_reference_id", data_type: "text" },
      { column_name: "signed_gdpr_document", data_type: "boolean" },
      { column_name: "archived_at", data_type: "number" },
      { column_name: "inactive_on", data_type: "number" },
      { column_name: "last_seen_at", data_type: "number" },
      { column_name: "bundle", data_type: "text" },
      { column_name: "accountant_id", data_type: "text" },
      { column_name: "accountant_name", data_type: "text" },
      { column_name: "accountant_is_partner_backoffice", data_type: "boolean" },
      { column_name: "currencies", data_type: "json" },
      { column_name: "default_currency", data_type: "text" },
      { column_name: "domain_wildcard_email", data_type: "text" },
      { column_name: "internal_email_support", data_type: "text" },
      { column_name: "internal_phone_number", data_type: "text" },
      { column_name: "internal_email_administration", data_type: "text" },
      { column_name: "supported_languages", data_type: "json" },
      { column_name: "is_partner_domain", data_type: "text" },
      { column_name: "subject_to_reverse_vat_charge", data_type: "boolean" },
      { column_name: "avatar", data_type: "text", hidden: true },
      { column_name: "metadata", data_type: "json" },
      { column_name: "company_country_number", data_type: "text" },
      { column_name: "payment_method_invoice", data_type: "text" },
      { column_name: "person_number_ref", data_type: "text" },
      { column_name: "person_number", data_type: "text" },
      { column_name: "birth_day", data_type: "text" },
      { column_name: "salutations", data_type: "text" },
      { column_name: "payment_term_invoice", data_type: "text" },
      { column_name: "label", data_type: "text" },
      { column_name: "language_invoice_and_quote", data_type: "text" },
      { column_name: "last_name", data_type: "text" },
      { column_name: "street", data_type: "text" },
      { column_name: "first_name", data_type: "text" },
      { column_name: "description", data_type: "text" },
      { column_name: "reverse_charged", data_type: "boolean" },
      { column_name: "awaiting_deletion", data_type: "boolean" },
      {
        column_name: "data_residency",
        data_type: "text",
        field_type: "select",
        options: [
          {
            label: "EU-DE",
            value: "EU-DE",
          },
          {
            label: "EU-FI",
            value: "EU-FI",
          },
          {
            label: "EU-NL",
            value: "EU-NL",
          },
          {
            label: "CA",
            value: "CA",
          },
          {
            label: "US-NY",
            value: "CA",
          },
        ],
      },
      { column_name: "custom_tags", data_type: "json" },
      { column_name: "dpa_signed", data_type: "boolean" },
      { column_name: "dpa_signed_url", data_type: "text" },
      { column_name: "dpa_signed_at", data_type: "number" },
      { column_name: "consent_marketing_communications", data_type: "boolean" },
      { column_name: "consent_marketing_data_provider", data_type: "text" },
      {
        column_name: "nsent_marketing_communications_given_at",
        data_type: "number",
      },
      {
        column_name: "consent_marketing_communications_preferences",
        data_type: "text",
      },
      { column_name: "lead_source", data_type: "text" },
      { column_name: "group_structure", data_type: "json" },
      { column_name: "onboarding_approved", data_type: "boolean" },
      { column_name: "onboarded_by_user", data_type: "text" },
      { column_name: "onboarding_aproval_conditions", data_type: "text" },
      { column_name: "onboarding_aproval_findings", data_type: "text" },
      { column_name: "is_oss", s: "boolean" },
      { column_name: "is_ioss", data_type: "boolean" },
      { column_name: "is_article23", data_type: "boolean" },
      {
        column_name: "kyc_status",
        data_type: "text",
        field_type: "select",
        update_column: "kyc_status",
        update_table: "customers",
        update_id_column: "customer_id",
        options: [
          { label: "Complete", value: "complete" },
          { label: "Incomplete", value: "incomplete" },
          { label: "Awaiting review", value: "awaiting_review" },
          { label: "Rejected", value: "rejected" },
        ],
      },
      { column_name: "payroll_withholding_number", data_type: "text" },
      { column_name: "risk_rating", data_type: "text" },
      { column_name: "pep_sanction_checked_at", data_type: "number" },
      { column_name: "is_pep_sanction", data_type: "boolean" },
      { column_name: "credit_limit", data_type: "number" },
      { column_name: "credit_debit_notes", data_type: "text" },
      { column_name: "credit_debit_arrangements", data_type: "text" },
      { column_name: "credit_hold_flags", data_type: "text" },
      { column_name: "customer_success_manager", data_type: "text" },
      { column_name: "store_user_ids", data_type: "text" },
      { column_name: "adverse_media_check_flags", data_type: "text" },
      { column_name: "adverse_media_checked_at", data_type: "number" },
      { column_name: "adverse_media_data_provider", data_type: "text" },
      { column_name: "invoicing_entity_legal_name", data_type: "text" },
      {
        column_name: "has_ultimate_beneficial_owner_statement",
        data_type: "boolean",
      },
      { column_name: "has_identity_card", data_type: "boolean" },
      { column_name: "has_business_registry_extract", data_type: "boolean" },
      { column_name: "has_power_of_attorney", data_type: "boolean" },
      { column_name: "has_source_of_wealth", data_type: "boolean" },
      { column_name: "has_source_of_funds", data_type: "boolean" },
      { column_name: "has_store_status", data_type: "boolean" },
      {
        column_name: "timezone",
        data_type: "text",
        category: "Basic",
        field_type: "select",
        options: timezoneKeys.map((key) => ({ label: key, value: key })),
      },
      { column_name: "language", data_type: "text", category: "Basic" },
      {
        column_name: "sla_agreed_response",
        data_type: "text",
        category: "Business",
      },
      {
        column_name: "sla_reporting_format_cadence",
        data_type: "text",
        category: "Business",
      },
      {
        column_name: "primary_ledger",
        data_type: "text",
        category: "Business",
      },
      {
        column_name: "primary_ledger_tenant_id",
        data_type: "text",
        category: "Business",
      },
      {
        column_name: "signed_contract",
        data_type: "text",
        category: "Legal",
      },
      {
        column_name: "rating_amount_questions",
        data_type: "string",
        category: "Client success",
        label: "Rating questions amount",
        field_type: "select",
        options: [
          {
            label: "Low",
            value: "low",
          },
          {
            label: "Normal",
            value: "normal",
          },
          {
            label: "High",
            value: "high",
          },
        ],
      },
      {
        column_name: "rating_difficult_admin",
        data_type: "string",
        category: "Client success",
        label: "Rating difficulty admin",
        field_type: "select",
        options: [
          {
            label: "Low",
            value: "low",
          },
          {
            label: "Normal",
            value: "normal",
          },
          {
            label: "High",
            value: "high",
          },
        ],
      },
      {
        column_name: "rating_responds_timely",
        data_type: "string",
        category: "Client success",
        label: "Rating respond time",
        field_type: "select",
        options: [
          {
            label: "Low",
            value: "low",
          },
          {
            label: "Normal",
            value: "normal",
          },
          {
            label: "High",
            value: "high",
          },
        ],
      },
      {
        column_name: "rating_payments",
        data_type: "string",
        category: "Client success",
        label: "Rating payments",
        field_type: "select",
        options: [
          {
            label: "Low",
            value: "low",
          },
          {
            label: "Normal",
            value: "normal",
          },
          {
            label: "High",
            value: "high",
          },
        ],
      },
    ] as ResourceFieldSpec[]),
  },
};

