import { defineAthenaResourceRoute } from "../constructors/define-athena-resource-route";
import type { ResourceRoute } from "../resource-types";
import { customersDataSource } from "./resource-route-data-sources";

export const transactionResourceRoutes: Record<string, ResourceRoute> = {
  transactions: {
    idColumn: "transaction_id",
    table: "stargate_ponto_transactions",
    companyIdColumn: "organization_id",
    searchBy: "transaction_id,description",
    force_remove_back_button_store_on_index_resource: true,
    columns: [
      {
        column_name: "transaction_id",
      },
      {
        column_name: "time",
      },
      {
        column_name: "ponto_account_id",
      },
      {
        column_name: "description",
      },
      {
        column_name: "amount",
      },
      {
        column_name: "currency",
      },
      {
        column_name: "counterpart_name",
        label: "Name counterpart",
      },
      {
        column_name: "counterpart_reference",
        label: "Reference counterpart",
      },
      {
        column_name: "remittance_information",
        label: "Remittance information",
      },
      {
        column_name: "promoted_to_transaction",
        label: "Promoted to transaction",
      },
    ],
  },
  invoices: defineAthenaResourceRoute("invoices", {
    table: "invoices",
    idColumn: "invoice_id",
    companyIdColumn: "organization_id",
    enableSearch: true,
    searchBy: "invoice_nr,recipient_company,status, ",
    deferNewButtonToHeader: true,
    deferTitleToHeader: true,
    deferSubtitleToHeader: true,
    deferToHeader: true,

    force_external_api_updates: true,
    enableNewResourceCreation: true,
    create: {
      scope: "",

      required: [],
      optional: [],
      columns: [
        { column_name: "recipient_email" },
        {
          column_name: "customer_id",
          header: "Customer",
          nullable: true,
          editor: {
            type: "select",
            data_source: customersDataSource,
          },
        },
        {
          column_name: "organization_id",
          hidden: true,
          default_value: "user.organization_id",
        },
        {
          column_name: "status",
          hidden: true,
          default_value: "pending",
        },
        {
          column_name: "ref_provider",
          hidden: true,
          default_value: "suitsbooks",
        },
      ],
    },
    force_no_cache: false,
    force_remove_back_button_store_on_index_resource: true,
    drilldownRoutePrefix: "/invoices",
    edit: {
      enabled: true,
      allowedColumns: [
        "recipient_name",
        "recipient_email",
        "invoice_nr",
        "recipient_postal_code",
        "recipient_phone",
        "recipient_first_name",
        "recipient_last_name",
        "recipient_address",
        "recipient_country",
        "due_date",
        "currency",
        "contact",
        "status",
        "recipient_company",
        "recipient_company_id",
        "paid",
        "author_name",
        "link_tos",
        "link_privacy_policy",
        "memo",
        "author_email",
        "author_postal_code",
        "author_phone",
        "author_first_name",
        "author_last_name",
        "author_address",
        "author_country",
        "author_company_id",
        "author_vat_id",
        "author_tax_id",
        "author_kvk",
        "recipient_kvk",
        "recipient_tax_id",
        "recipient_vat_id",
        "amount",
        "amount_paid",
        "amount_remaining",
        "paid_at",
        "payment_method",
        "number_format",
        "email_sent",
        "email_id",
        "email_sent_at",
        "times_opened",
        "times_opened_unique",
        "company_logo",
        "company_logo_href",
        "discount_code",
        "discount_total",
        "discount",
        "shipping_rate",
        "shipping_total",
        "send_as_email",
        "subscription",
        "subscription_id",
        "relation_hash",
        "scheduled_email_send_at",
        "descriptor_global",
        "descriptor_relation",
        "number_global",
        "number_relation",
        "url",
        "brand_color",
        "pdf_generated",
        "pdf_url",
        "reverse_charged",
        "invoice_template_id",
        "custom_fields",
        "tax_id_type_recipient",
        "tax_id_type_author",
        "descriptor_project",
        "views",
        "revenue",
        "sales",
        "note",
        "url_link_deactivated",
        "total_fmt",
        "subtotal_fmt",
        "tax_total_fmt",
        "has_payment_callback",
        "payment_method_count",
        "invoice_age_days_past_due",
        "payment_methods",
        "creator_ip_address",
        "author_tax_country",
        "recipient_tax_country",
        "issue_date",
        "payment_method_ids",
        "footer",
        "slug",
        "subtotal",
        "tax_amount",
        "total",
        "idempotency_key",
        "payment_method_configuration_id",
        "language",
        "amount_paid_fmt",
        "amount_remaining_fmt",
        "tax_rate",
        "time_creation",
        "recipient_billing_street",
        "recipient_shipping_street",
        "recipient_billing_house_number",
        "recipient_shipping_house_number",
        "recipient_billing_country",
        "recipient_shipping_country",
        "recipient_shipping_province",
        "recipient_shipping_city",
        "tax_exempt",
        "tax_inclusive",
        "receipt_url",
        "awaiting_archival",
        "reconciliation_id",
        "quote_id",
        "customer_id",
        "global_company_id",
        "amount_due_fmt",
        "ref_identifier",
        "ref_provider",
        "total_incl_vat",
        "document_type",
        "cancelled_at",
      ],
    },
    columns: [
      {
        column_name: "created_at",
        maxWidth: 100,
      },
      {
        column_name: "total",
        maxWidth: 100,
      },
      {
        column_name: "status",
        maxWidth: 100,
        order: 1,
        editable: {
          type: "select",
          options: [
            { label: "Draft", value: "draft" },
            { label: "Pending", value: "pending" },
            { label: "Paid", value: "paid" },
            { label: "Overdue", value: "overdue" },
            { label: "Cancelled", value: "cancelled" },
          ],
          update_table: "invoices",
          update_column: "status",
          update_id_column: "invoice_id",
        },
      },
      {
        column_name: "invoice_nr",
        header_label: "Invoice number",
        widthFit: true,
        formatter: (value: unknown) =>
          typeof value === "string" ? value.toUpperCase() : value,
      },
      {
        column_name: "customer_id",
        href: "/v2/customers/{{customer_id}}",
        cell_value_mask_label: "{{recipient_company}}",
        header_label: "Customer",
        maxWidth: 100,
      },
      {
        column_name: "currency",
        hidden: true,
      },
      {
        column_name: "due_date",
      },

      {
        column_name: "invoice_id",
        cell_value_mask_label: "{{invoice_nr}}",
        order: 3,
      },
      {
        column_name: "issue_date",
      },
      {
        column_name: "recipient_company",
        hidden: true,
      },
      {
        column_name: "paid",
        data_type: "boolean",
        editable: {
          type: "boolean",
        },
      },
      {
        column_name: "tax_exempt",
        data_type: "boolean",
        editable: {
          type: "boolean",
        },
        hidden: true,
      },
      {
        column_name: "awaiting_archival",
        data_type: "boolean",
        editable: {
          type: "boolean",
        },
        hidden: true,
      },
      {
        column_name: "tax_inclusive",
        data_type: "boolean",
        editable: {
          type: "boolean",
        },
        hidden: true,
      },
      {
        column_name: "reverse_charged",
        data_type: "boolean",
        editable: {
          type: "boolean",
        },
        hidden: true,
      },
      {
        column_name: "pdf_generated",
        data_type: "boolean",
        editable: {
          type: "boolean",
        },
        hidden: true,
      },
      {
        column_name: "has_payment_callback",
        data_type: "boolean",
        editable: {
          type: "boolean",
        },
        hidden: true,
      },
      {
        column_name: "subscription",
        data_type: "boolean",
        editable: {
          type: "boolean",
        },
        hidden: true,
      },
      {
        column_name: "send_as_email",
        data_type: "boolean",
        editable: {
          type: "boolean",
        },
        hidden: true,
      },
      {
        column_name: "shipping_rate",
        data_type: "boolean",
        editable: {
          type: "boolean",
        },
        hidden: true,
      },
      {
        column_name: "email_sent",
        data_type: "boolean",
        editable: {
          type: "boolean",
        },
        hidden: true,
      },
      {
        column_name: "url_link_deactivated",
        data_type: "boolean",
        editable: {
          type: "boolean",
        },
        hidden: true,
      },
      {
        column_name: "time_creation",
        data_type: "date",
        editable: {
          type: "text",
        },
        hidden: true,
      },
      {
        column_name: "slug",
        data_type: "string",
        editable: {
          type: "text",
        },
        hidden: true,
      },
    ],
  }),

  cases: {
    table: "v_cases",
    idColumn: "ticket_id",
    page_label: "Cases",
    sidebar_route: "/sf-formations",
    companyIdColumn: "company_id",
    enableSearch: true,
    searchBy: "title,status,ticket_id,description,ticket_number",
    drilldownRoutePrefix: "/cases",
    chat: {
      table: "customer_messages",
      foreignKeyColumn: "message_id",
      messageColumn: "message",
      authorUserIdColumn: "author_user_id",
    },
    columns: [
      { column_name: "status", order: 1, maxWidth: 80 },
      { column_name: "priority", order: 2, maxWidth: 80 },
      { column_name: "title", order: 3, maxWidth: 180 },
      { column_name: "assignees", maxWidth: 80, order: 4 },
      { column_name: "created_at" },
      { column_name: "close_reason" },
      { column_name: "scope" },
      { column_name: "bucket" },
      { column_name: "company_id", hidden: true },
    ],
  },
};

